version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - aws s3 cp s3://loumistest/index.html .
  build:
    commands:
      - aws s3 cp index.html s3://loumistest/
